openapi: 3.0.3
info:
  title: Loan Eligibility API
  version: 1.1.0
  description: >
    Single microservice. Validates loan eligibility using rules R1–R4.
servers:
  - url: http://localhost:8080
paths:
  /api/loan-eligibility:
    post:
      summary: Validate loan eligibility
      operationId: validateLoanEligibility
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanValidationRequest'
            examples:
              ok:
                value:
                  monthlySalary: 2500
                  requestedAmount: 6000
                  termMonths: 24
                  employmentMonths: 12
      responses:
        '200':
          description: Eligibility evaluation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoanValidationResponse'
components:
  schemas:
    LoanValidationRequest:
      type: object
      required: [monthlySalary, requestedAmount, termMonths, employmentMonths]
      properties:
        monthlySalary: { type: number, format: double, minimum: 1 }
        requestedAmount: { type: number, format: double, minimum: 1 }
        termMonths: { type: integer, minimum: 1, maximum: 36 }
        employmentMonths: { type: integer, minimum: 0, description: "R1: debe ser >= 3" }
    LoanValidationResponse:
      type: object
      required: [eligible, monthlyPayment, reasons]
      properties:
        eligible: { type: boolean }
        monthlyPayment: { type: number, format: double }
        reasons:
          type: array
          items: { type: string }
