openapi: 3.0.3
info:
  title: Loan Validation API
  version: 1.0.0
paths:
  /loan-validations:
    post:
      summary: Valida un préstamo
      operationId: validateLoan
      tags: [loan-validations]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanValidationRequest'
      responses:
        '200':
          description: Resultado de validación
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoanValidationResult'
components:
  schemas:
    LoanValidationRequest:
      type: object
      required: [monthlySalary, requestedAmount, termMonths]
      properties:
        monthlySalary: { type: number, format: double, minimum: 0.01 }
        requestedAmount: { type: number, format: double, minimum: 0.01 }
        termMonths: { type: integer, minimum: 1, maximum: 36 }
        lastLoanDate:
          type: string
          format: date
          nullable: true
          description: Fecha del último préstamo del solicitante.
    LoanValidationResult:
      type: object
      required: [eligible, reasons, monthlyPayment]
      properties:
        eligible: { type: boolean }
        reasons:
          type: array
          items:
            type: string
            enum: [HAS_RECENT_LOANS, PLAZO_MAXIMO_SUPERADO, CAPACIDAD_INSUFICIENTE, DATOS_INVALIDOS]
        monthlyPayment: { type: number, format: double }
